### ISSUE TITLE
need to specify python's compatible version

### ISSUE THREAD

**Issue by Quantum-dogdog** [weasdown/GMAT-Python-simple#5]
first of all, great project!

it seems like you are using python3.10,

my python version is 3.9.6,so it shows:

         TypeError: unsupported operand type(s) for |: 'type' and 'type'

i have to modify gmat_py_simple\executive.py line231 to

         if isinstance(com, (gpy.BranchCommand,gmat.BranchCommand)):

& commands.py has the same bug.

then i can run  Tut01 & Tut02 success.

**Comment by weasdown** [comment]
I've added a warning about Python versions to [README.md](https://github.com/weasdown/GMAT-Python-simple/blob/2f188c2ae137b1b879046e03f25701ef0b8bed7f/README.md). @Quantum-dogdog, is that the sort of version specifying you're looking for?

**Comment by Quantum-dogdog** [comment]
That's nice!
